# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://kuraiandras.github.io/'
baseurl: ''
title: 'YAYADB'
description: 'Yet Another Yet Another Dev Blog'
permalink: pretty
logo: "http://www.gravatar.com/avatar/6bb8645c6a81d34a5a34742c905df8a7.jpg?s=52"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: About
  url: /about/
- title: Blog
  url: /blog/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "Blog posts"
    feature_text: |
      ## YAYADB
    feature_image: "https://picsum.photos/2560/600?image=866"
